import {useEffect,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {EChart} from '../research/charts/EChart';
type Obj=Record<string,any>;
export const emergenceDefaults={experiment_mode:'emergent_specialization',name:'Emergent Specialization',source_mode:'sweep',source_sweep:'',common_checkpoint:'',family:'gpt',expert_count:4,seeds:[42,43,44],asymmetry_type:'weight_perturbation',asymmetry_strengths:[0,.001,.01,.05],feedback_strengths:[0,.25,.5],design:'narrow',include_oracle:false,train_steps:250,batch_size:4,expert_learning_rate:.001,exploration:.2,probe_interval:50,probe_samples:256,validation_samples:200,evaluation_samples:300,diagnostic_samples:400,reference_size:128,fit_epochs:80,learning_rate:.001,checkpoints:[0,.1,.25,.5,.75,1],descriptor_set:'full',spectral_enabled:false,device:'cpu',tie_epsilon:.001,success_quantile:.2};
const fmt=(v:any)=>typeof v==='number'&&Number.isFinite(v)?v.toFixed(4):'—';
function ListInput({label,value,onChange}:{label:string;value:number[];onChange:(v:number[])=>void}){
 const [draft,setDraft]=useState(value.join(', '));useEffect(()=>setDraft(value.join(', ')),[JSON.stringify(value)]);
 return <label>{label}<input value={draft} onChange={e=>setDraft(e.target.value)} onBlur={()=>onChange(draft.split(',').map(v=>v.trim()===''?NaN:Number(v)))}/></label>;
}
export function EmergenceSetup({config:c,setConfig,runs}:{config:Obj;setConfig:(v:any)=>void;runs:Obj[]}){
 const [source,setSource]=useState<Obj>(),[error,setError]=useState('');
 const available=runs.filter(r=>r.experiment_type==='token_lab_sweep'),chosen=available.find(r=>r.runDirectory===c.source_sweep);
 useEffect(()=>{let gone=false;setSource(undefined);setError('');if(chosen)void invoke<Obj>('get_token_lab',{runId:chosen.run_id}).then(v=>{if(!gone)setSource(v);}).catch(e=>{if(!gone)setError(String(e));});return()=>{gone=true;};},[chosen?.run_id]);
 const set=(k:string,v:any)=>setConfig((old:Obj)=>({...old,[k]:v}));
 const field=(k:string,label:string,min=1,step=1)=><label key={k}>{label}<input type="number" min={min} step={step} value={c[k]} onChange={e=>set(k,+e.target.value)}/></label>;
 const entries:Obj[]=(source?.analysis?.sweep?.entries??[]).filter((e:Obj)=>e.family===c.family&&e.strength===1&&e.status==='completed');
 const sourceSeeds=[...new Set(entries.map(e=>e.seed))].sort((a,b)=>a-b);
 const aa=[...new Set<number>(c.asymmetry_strengths)].filter(a=>a>0).sort((a,b)=>a-b),bb=[...new Set<number>(c.feedback_strengths)].filter(b=>b>0).sort((a,b)=>a-b);
 const pairs=aa.flatMap(a=>bb.filter(b=>c.design==='factorial'||b===bb.at(-1)||a===aa[Math.floor(aa.length/2)]).map(b=>[a,b]));
 const jobs=(1+aa.length+bb.length+pairs.length*(c.include_oracle?3:2))*c.seeds.length;
 const preset=(kind:string)=>setConfig((old:Obj)=>({...old,...(kind==='smoke'?{expert_count:old.family==='mixed'?4:2,seeds:[sourceSeeds[0]??old.seeds[0]??42],asymmetry_strengths:[0,.01],feedback_strengths:[0,.5],train_steps:10,batch_size:2,probe_interval:10,probe_samples:20,validation_samples:20,evaluation_samples:20,diagnostic_samples:200,reference_size:20,fit_epochs:2,checkpoints:[0,1],design:'narrow'}:{...Object.fromEntries(Object.entries(emergenceDefaults).filter(([k])=>!['source_mode','source_sweep','common_checkpoint','family','device','name','seeds'].includes(k))),...(old.family==='mixed'?{expert_count:4,asymmetry_strengths:[0,.01]}:{}),seeds:sourceSeeds.length>=3?(old.family==='mixed'?sourceSeeds:sourceSeeds.slice(0,3)):[42,43,44],design:kind==='factorial'?'factorial':'narrow'})}));
 return <section className="panel" style={{gridColumn:'1 / -1'}}><h3>Emergent Specialization</h3>
  <p>Start from a general common bank: identical clones in homogeneous mode, jointly pretrained GPT/SSM/GRU/Delta in mixed mode. Apply optional small weight perturbations without task roles, then compare matched exposure controls. Shared encoder/readout stay frozen; only experts and the existing competence learner train. Single-step residual application.</p>
  <div className="lab-actions"><button type="button" onClick={()=>preset('smoke')}>Smoke test preset</button><button type="button" onClick={()=>preset('narrow')}>Narrow study preset</button><button type="button" onClick={()=>preset('factorial')}>Full grid preset</button></div>
  <div className="lab-fields">
   <label>Study name<input value={c.name} onChange={e=>set('name',e.target.value)}/></label>
   <label>Common base source<select value={c.source_mode} onChange={e=>set('source_mode',e.target.value)}><option value="sweep">General bases from saved validation sweep</option><option value="checkpoint">One general common-base.pt for every seed</option></select></label>
   {c.source_mode==='sweep'?<label>Source validation sweep<select aria-label="Emergence source validation sweep" value={chosen?.run_id??''} onChange={e=>set('source_sweep',available.find(r=>r.run_id===e.target.value)?.runDirectory??'')}><option value="">Choose your saved sweep</option>{available.map(r=><option key={r.run_id} value={r.run_id}>{r.name} · {r.run_id} · {r.status}</option>)}</select></label>:<label>General common-base.pt path<input value={c.common_checkpoint} onChange={e=>set('common_checkpoint',e.target.value)}/></label>}
   <label>Expert family<select value={c.family} onChange={e=>setConfig((old:Obj)=>({...old,family:e.target.value,expert_count:e.target.value==='mixed'?4:old.expert_count,...(e.target.value==='mixed'?{asymmetry_strengths:[0,.01]}:{})}))}>{['gpt','ssm','recurrent','delta','mixed'].map(f=><option key={f} value={f}>{f==='mixed'?'Mixed GPT + SSM + GRU + Delta':f==='recurrent'?'Recurrent / GRU':f.toUpperCase()}</option>)}</select></label>
   <label>Expert count<select disabled={c.family==='mixed'} value={c.expert_count} onChange={e=>set('expert_count',+e.target.value)}>{[2,4,8].map(n=><option key={n}>{n}</option>)}</select></label>
   <ListInput label="Matched seeds (comma separated)" value={c.seeds} onChange={v=>set('seeds',v)}/>
   <ListInput label="Asymmetry strengths (include 0)" value={c.asymmetry_strengths} onChange={v=>set('asymmetry_strengths',v)}/>
   <ListInput label="Competence feedback strengths (include 0)" value={c.feedback_strengths} onChange={v=>set('feedback_strengths',v)}/>
   <label>Sweep design<select value={c.design} onChange={e=>set('design',e.target.value)}><option value="narrow">Narrow: all asymmetries at max feedback; middle asymmetry at all feedback levels</option><option value="factorial">Full factorial</option></select></label>
   {field('train_steps','Training update blocks')}{field('batch_size','Mixed endpoints per block')}{field('expert_learning_rate','Expert learning rate',.000001,.0001)}{field('exploration','Uniform exploration fraction',.01,.05)}
   <label>Device<select value={c.device} onChange={e=>set('device',e.target.value)}><option>cpu</option><option>cuda</option></select></label>
  </div>
  {source&&<p>Available general-base seeds for {c.family}: {sourceSeeds.join(', ')||'none'}. <button type="button" onClick={()=>set('seeds',sourceSeeds)}>Use all available seeds</button></p>}
  {c.family==='mixed'&&<p>Use a heterogeneous validation sweep. A is a mixed equal-exposure baseline; experts already differ by architecture at zero perturbation. Cross-family parameter distances are unavailable; functional differences and held-out gains are measured normally.</p>}
  <p>Automatically restores model dimensions, tokenizer, context length and neighbourhood from the general base. The sweep's 100% job supplies its saved <strong>pre-specialization common-base.pt</strong>; its specialist weights and assigned tasks are never loaded.</p>
  <p><strong>{jobs} condition/seed jobs; {(jobs*c.train_steps*c.batch_size*c.expert_count).toLocaleString()} expert training applications.</strong> Probing and predictive analysis are additional; Validate gives their estimated counts. Each input supplies one training ticket per expert; feedback redirects a fraction of tickets. Random controls shuffle learned ticket assignments while keeping exactly the same expert counts per block.</p>
  <p>Weight asymmetry α means ‖perturbation‖ / ‖common expert parameters‖ = α. Default 0, 0.001, 0.01, 0.05 = 0%, 0.1%, 1%, 5%. At zero, weights are unchanged; clone identity is required only for homogeneous populations. No task labels enter the router.</p>
  <details><summary>Counterfactual evidence, checkpoint and analysis budgets</summary><div className="lab-fields">
   {field('probe_interval','Router refresh interval (blocks)')}{field('probe_samples','Router training probe states',20)}{field('validation_samples','Router validation states',20,10)}{field('evaluation_samples','Matched held-out utility states',20,10)}{field('diagnostic_samples','Separate detectability states',100,10)}{field('reference_size','Training-only novelty reference size',10)}{field('fit_epochs','Router fitting epochs')}{field('learning_rate','Router learning rate',.000001,.0001)}
   <ListInput label="Checkpoint fractions (include 0 and 1)" value={c.checkpoints} onChange={v=>set('checkpoints',v)}/>
   <label>Router descriptors<select value={c.descriptor_set} onChange={e=>set('descriptor_set',e.target.value)}><option value="full">Validated full descriptors</option><option value="controls">Simple controls comparison</option></select></label>
   <label><input type="checkbox" checked={c.spectral_enabled} onChange={e=>set('spectral_enabled',e.target.checked)}/> Add spectral measurements (secondary test)</label>
   <label><input type="checkbox" checked={c.include_oracle} onChange={e=>set('include_oracle',e.target.checked)}/> Include privileged oracle-feedback reference F</label>
   {field('tie_epsilon','Loss tie tolerance (nats)',.000001,.001)}{field('success_quantile','Success upper-tail fraction',.01,.05)}
  </div></details>
  <p>Always saves raw observations, matched panels, assignment counts, expert/router checkpoints and report. Reopening results never changes these settings. Two-expert routing reuses the validated decision rule. Four/eight experts combine the same pairwise learners by pairwise win count, using mean preference to break ties; that population extension is part of this experiment.</p>
  <p>Start with Smoke test, then Narrow study with at least three matched seeds. A one-seed smoke run always receives INCONCLUSIVE research verdicts. Common-base training is reused, not rerun.</p>
  {error&&<p role="alert">{error}</p>}
 </section>;
}
function line(title:string,points:Obj[],series:Array<[string,(v:Obj)=>any]>,axis='Training blocks'){
 return {animation:false,title:{text:title,textStyle:{fontSize:13,color:'#ddd'}},tooltip:{trigger:'axis'},legend:{top:25,textStyle:{color:'#aaa'}},grid:{left:65,right:40,top:75,bottom:55},xAxis:{type:'value',name:axis},yAxis:{type:'value',scale:true},series:series.map(([name,get])=>({name,type:'line',showSymbol:true,data:points.map(v=>[v.step,get(v)])}))};
}
export function EmergenceProgress({events,progress}:{events:Obj[];progress?:Obj}){
 const last=events.at(-1),points=events.filter(e=>e.seed===last?.seed&&e.condition_id===last?.condition_id);
 return <section className="panel"><h3>Emergence checkpoint progress</h3><p>{progress?.phase} · {progress?.completed_jobs??0}/{progress?.planned_jobs??'—'} completed jobs. Checkpoint evaluations do not guide training.</p>{last?<><p>Seed {last.seed} · {last.condition_id}</p><EChart replace option={line('Held-out loss',points,[['Online router',v=>v.loss]])}/><EChart replace option={line('Functional divergence and routing benefit',points,[['Interaction RMS',v=>v.interaction_rms],['Gain over fixed',v=>v.router_gain]])}/></>:<p>Preparing identical clones and disjoint data panels. The first graphs appear after the initialization checkpoint.</p>}</section>;
}
export function EmergenceResults({detail}:{detail:Obj}){
 const a=detail.analysis.emergence,complete:Obj[]=a.entries.filter((e:Obj)=>e.status==='completed');
 const [selection,setSelection]=useState(''),[x,setX]=useState('blocks');
 const selected=complete.find(e=>`${e.seed}/${e.id}`===selection)??complete[0],points:Obj[]=selected?.checkpoints??[];
 const coord=(p:Obj)=>x==='applications'?p.cost.training_applications+p.cost.probe_applications+p.cost.oracle_training_applications:x==='tokens'?p.cost.training_context_tokens:p.step;
 const transformed=points.map(p=>({...p,step:coord(p)}));
 const conditions:Obj=a.summary?.conditions??{},paired:Obj=a.summary?.paired_comparisons??{};
 const avg=(values:any[])=>{const v=values.filter(v=>typeof v==='number');return v.length?v.reduce((s,a)=>s+a,0)/v.length:null;};
 return <section className="panel"><h2>Emergent Specialization results</h2><p>{a.status} · {complete.length}/{a.planned_jobs} complete. Emergence, detection and utility are evaluated separately. All findings are exploratory; no single run validates the architecture.</p>
  <div className="lab-fields"><label>Individual seed / condition<select value={selected?`${selected.seed}/${selected.id}`:''} onChange={e=>setSelection(e.target.value)}>{complete.map(e=><option key={`${e.seed}/${e.id}`} value={`${e.seed}/${e.id}`}>Seed {e.seed} · {e.id}</option>)}</select></label><label>Curve horizontal axis<select value={x} onChange={e=>setX(e.target.value)}><option value="blocks">Training blocks</option><option value="tokens">Training context token exposures</option><option value="applications">Training + probe expert applications (not FLOPs)</option></select></label></div>
  <h3>Emergence</h3><EChart replace option={line('Functional differences on matched held-out states',transformed,[['State × expert interaction RMS',v=>v.specialization.interaction_rms],['Oracle gain over best constant',v=>v.specialization.oracle_gain_over_best_constant]],x)}/>
  <p>Interaction RMS removes global expert strength and common token difficulty. Weight distance alone does not establish specialization.</p><EChart replace option={line('Competence stability',transformed,[['Adjacent advantage correlation',v=>v.stability.mean_advantage_correlation]],x)}/>
  <h3>Detectability</h3><EChart replace option={line('Held-out predictive probes · mean over experts',transformed,[['Ridge R²',v=>avg(Object.values(v.detectability).map((d:any)=>d.ridge?.test.r2))],['MLP R²',v=>avg(Object.values(v.detectability).map((d:any)=>d.mlp?.test.r2))],['Success ROC-AUC',v=>avg(Object.values(v.detectability).map((d:any)=>d.success_classifier?.test.roc_auc))]],x)}/>
  <p>Predicting improvement can reflect common difficulty. Require state-dependent selection gains and distinct competence signatures as well.</p>
  <h3>Utility</h3>{selected?.condition==='F'&&<p>F uses privileged counterfactual oracle selection. It has no trained router and cannot support H2.</p>}<EChart replace option={line('Final next-token loss · lower is better',transformed,[[selected?.condition==='F'?'Privileged oracle policy':'Competence policy',v=>v.utility.policy_loss],['Training-selected fixed',v=>v.utility.fixed],['Expected uniform random',v=>v.utility.uniform],['Round robin',v=>v.utility.round_robin],['Counterfactual oracle',v=>v.utility.oracle]],x)}/><EChart replace option={line('Routing loss reduction · positive is better',transformed,[['Gain over fixed',v=>v.utility.gain_over_fixed],['Gain over random',v=>v.utility.gain_over_random]],x)}/>
  <h3>Seed consistency and separate hypotheses</h3><div className="lab-table"><table><thead><tr><th>Condition</th><th>Seeds</th><th>Final NLL mean / SD</th><th>95% seed interval</th><th>H1 emergence</th><th>H2 detection</th><th>H3 utility</th></tr></thead><tbody>{Object.entries(conditions).map(([k,g]:any)=><tr key={k}><td>{k}</td><td>{g.seeds.join(', ')}</td><td>{fmt(g.final_loss.mean)} / {fmt(g.final_loss.std)}</td><td>{g.final_loss.ci?.map(fmt).join(' … ')??'Unavailable'}</td><td>{g.hypothesis_1}</td><td>{g.hypothesis_2}</td><td>{g.hypothesis_3}</td></tr>)}</tbody></table></div>
  <h3>Controls · paired causal comparisons</h3><p>Negative loss difference favors the left condition. B−A: asymmetry; C−A: feedback without perturbation; D−B: feedback added; D−E: competence versus matched random exposure; F−D: privileged reference.</p><table><thead><tr><th>Comparison</th><th>Seeds</th><th>Mean NLL difference</th><th>95% paired seed interval</th></tr></thead><tbody>{Object.entries(paired).map(([k,g]:any)=><tr key={k}><td>{k}</td><td>{g.seeds.join(', ')}</td><td>{fmt(g.loss_difference.mean)}</td><td>{g.loss_difference.ci?.map(fmt).join(' … ')??'Unavailable'}</td></tr>)}</tbody></table>
  {selected&&<><h3>Expert opportunity and collapse checks</h3><EChart replace option={{animation:false,tooltip:{trigger:'axis'},legend:{},xAxis:{type:'category',data:selected.final.exposure.map((_:any,i:number)=>`Expert ${i+1}`)},yAxis:{type:'value'},series:[{type:'bar',name:'Training applications',data:selected.final.exposure},{type:'bar',name:'Counterfactual applications',data:selected.final.probes_per_expert}]}}/>{points.flatMap(p=>p.warnings.map((w:string)=><p key={`${p.step}-${w}`}>Step {p.step}: {w}</p>))}<details><summary>Individual predictive metrics, parameter distances, timing and checkpoint records</summary><pre>{JSON.stringify(selected,null,2)}</pre></details><details><summary>Post-hoc task reveal · never used for assignment</summary><pre>{JSON.stringify(selected.final.reveal,null,2)}</pre></details></>}
  {a.entries.filter((e:Obj)=>e.status!=='completed').map((e:Obj)=><p role="alert" key={`${e.seed}/${e.id}`}>Seed {e.seed} {e.id}: {e.status} — {e.error}</p>)}
  <h3>Report</h3><p>Share report.md and emergence-analysis.json. Saved results reopen without training. Checkpoint folders contain expert and router weights plus raw counterfactual observations.</p><pre className="lab-report">{detail.report}</pre>
 </section>;
}
